# permissions for end users to edit configurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: api-configuration-editor-role
rules:
- apiGroups:
  - api.cloud.cloudsteak.com
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.cloud.cloudsteak.com
  resources:
  - configurations/status
  verbs:
  - get
